### PR TITLE
weather application

### PR DESCRIPTION
**Pull request by PAARTH2608**
WEATHER APPLICATION USING HTML, CSS, JS

### CODE REVIEW

**Comment by Manasvi070902** [comment]
Files not visible
Kindly add README with screenshots of our app too.

**Comment by PAARTH2608** [comment]
What else i can improve in this?

**Comment by Manasvi070902** [comment]
Can you share screenshot of your app?

**Comment by PAARTH2608** [comment]
Sure

**Comment by PAARTH2608** [comment]
Screenshot (784)

**Pull request closed without merging**
